[package]
name = "xch"
version = "0.1.0"
authors = ["WanzenBug <moritz.wanzenboeck@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/WanzenBug/xch"
documentation = "https://docs.rs/xch"
description = """
A CLI utility and rust crate to atomically swap the content of two paths.
"""

categories = ["filesystem"]
keywords = ["fs", "file", "filesystem", "cli"]

pre-release-commit-message = "Release {{version}}"
pre-release-replacements = [
    {file="README.md", search="Current release: [a-z0-9\\.-]+", replace="Current release: {{version}}"},
    {file="README.md", search="xch = \"[a-z0-9\\.-]+\"", replace="xch = \"{{version}}\""},
]

[lib]
name = "libxch"
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "xch"
doc = false

[target."cfg(windows)".dependencies]
winapi = "^0.2.8"
kernel32-sys = "^0.2.2"
ktmw32-sys = "^0.1.0"

[dependencies]
error-chain = "^0.10.0"
clap = "2.26.0"

[dev-dependencies]
tempdir = "0.3"
